/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expensetracker;

import com.toedter.calendar.JDateChooser;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Prim
 */
public class expense extends javax.swing.JFrame {

    Connection con;
    PreparedStatement stm;

    Login_page login = new Login_page();
    static String next = "";

    public expense() {
        initComponents();
        Connect();
        updateCombo();
        login.info(next);

    }
    public String User_ID = login.userId;

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/expensetracker_db", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Income.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Income.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void updateCombo() {
        String sql = "SELECT * FROM category_table WHERE CategoryType= 'Expense'";
        try {
            stm = con.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();

            while (rs.next()) {
                expensecat.addItem(rs.getString("CategoryName"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Income.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     private boolean isValidAmount(String amount) {
        try {
            Double.parseDouble(amount);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        expensecat = new javax.swing.JComboBox<>();
        expensebtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jdate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 224, 224));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(173, 128, 171));
        jLabel1.setText("Input Expense");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(173, 128, 171));
        jLabel2.setText("Category");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(173, 128, 171));
        jLabel3.setText("Amount:");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(173, 128, 171));
        jLabel4.setText("Description");

        amount.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        amount.setForeground(new java.awt.Color(173, 85, 146));
        amount.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        expensecat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 85, 146), 2, true));
        expensecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensecatActionPerformed(evt);
            }
        });

        expensebtn.setBackground(new java.awt.Color(173, 128, 171));
        expensebtn.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        expensebtn.setForeground(new java.awt.Color(255, 255, 255));
        expensebtn.setText("Submit");
        expensebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensebtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(173, 128, 171));
        jLabel5.setText("Date");

        jButton2.setBackground(new java.awt.Color(173, 128, 171));
        jButton2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 85, 146), 2, true));
        jdate.setForeground(new java.awt.Color(173, 85, 146));

        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        desc.setRows(5);
        desc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(173, 85, 146), 2, true));
        jScrollPane1.setViewportView(desc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expensecat, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(expensebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expensecat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expensebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void expensecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensecatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_expensecatActionPerformed

    private void expensebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensebtnActionPerformed

        String Category, Description, Date;
        String Amount;

        String url = "jdbc:MySQL://localhost:3306/expensetracker_db";
        String suser = "root";
        String spass = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, suser, spass);

            if ("".equals(jdate.getDateFormatString()) || jdate.getDate() == null) {
                JOptionPane.showMessageDialog(new JFrame(), "Date is required!", "Error!", JOptionPane.WARNING_MESSAGE);

            }else if(!isValidAmount(amount.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Invalid Amount!", "Error!", JOptionPane.WARNING_MESSAGE);
                
            }else if ("".equals(amount.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Amount is required!", "Error!", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(desc.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Description is required!", "Error!", JOptionPane.WARNING_MESSAGE);
            } else if (expensecat.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(new JFrame(), "Category is required!", "Error!", JOptionPane.WARNING_MESSAGE);
            } else {

                Description = desc.getText();
                JDateChooser jDateChooser = (JDateChooser) jdate;
                java.util.Date selectedDate = jDateChooser.getDate();
                java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime()); // Convert util.Date to sql.Date

                Amount = amount.getText();
                Category = expensecat.getSelectedItem().toString();
                double expenseAmount = Double.parseDouble(Amount);
                String getBalanceQuery = "SELECT BalanceID, BalanceAmount FROM balance_table WHERE UserID = ?";
                PreparedStatement getBalanceStmt = con.prepareStatement(getBalanceQuery);
                getBalanceStmt.setString(1, User_ID);
                ResultSet rs = getBalanceStmt.executeQuery();

                int BalanceID = -1;
                double currentBalance = 0.0;
                if (rs.next()) {
                    BalanceID = rs.getInt("BalanceID");
                    currentBalance = rs.getDouble("BalanceAmount");
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Balance not Enough! Check your balance!", "Error!", JOptionPane.WARNING_MESSAGE);
                    con.rollback();
                    return;
                }

                double newBalance = currentBalance - expenseAmount;

                String updateBalanceQuery = "UPDATE balance_table SET BalanceAmount = ? WHERE BalanceID = ?";
                PreparedStatement updateBalanceStmt = con.prepareStatement(updateBalanceQuery);
                updateBalanceStmt.setDouble(1, newBalance);
                updateBalanceStmt.setInt(2, BalanceID);
                updateBalanceStmt.executeUpdate();

                String expenseQuery = "INSERT INTO expense_table (UserID, CategoryID, BalanceID, Amount, Description, Date) "
                        + "VALUES (?, (SELECT CategoryID FROM category_table WHERE CategoryName = ?), ?, ?, ?, ?)";
                PreparedStatement expenseStmt = con.prepareStatement(expenseQuery, Statement.RETURN_GENERATED_KEYS);
                expenseStmt.setString(1, User_ID);
                expenseStmt.setString(2, Category);
                expenseStmt.setInt(3, BalanceID);
                expenseStmt.setDouble(4, expenseAmount);
                expenseStmt.setString(5, Description);
                expenseStmt.setDate(6, sqlDate);
                expenseStmt.executeUpdate();

                ResultSet expenseGeneratedKeys = expenseStmt.getGeneratedKeys();
                int ExpenseID = -1;
                if (expenseGeneratedKeys.next()) {
                    ExpenseID = expenseGeneratedKeys.getInt(1);
                } else {
                    throw new SQLException("Creating expense record failed, no ID obtained.");
                }

                String transactionQuery = "INSERT INTO transaction_table (UserID, BalanceID, ExpenseID) VALUES (?, ?, ?)";
                PreparedStatement transactionStmt = con.prepareStatement(transactionQuery);
                transactionStmt.setString(1, User_ID);
                transactionStmt.setInt(2, BalanceID);
                transactionStmt.setInt(3, ExpenseID);
                transactionStmt.executeUpdate();

                desc.setText("");
                amount.setText("");
                expensecat.setSelectedItem("");

                JOptionPane.showMessageDialog(this, "Added!");
                con.close();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(expense.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(expense.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_expensebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new ET_Homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new expense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextArea desc;
    private javax.swing.JButton expensebtn;
    private javax.swing.JComboBox<String> expensecat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate;
    // End of variables declaration//GEN-END:variables
}
